### PR TITLE
add folder encrypt feature

### PR DESCRIPTION
**Pull request by lucabello**
Hello!
A little while ago, I opened issue #39 hoping to get a feature to encrypt a specific folder on my vault on demand. I reckon that use case is very popular, as currently there is just no way to do it through an Obsidian Plugin.

I took the liberty to expand on your code and make that feature myself, as we mentioned in the issue above. However, now that some more time has passed and the plugin has had quite many updates (which are great, by the way), I'm wondering if you would consider this feature still out of scope or not.

Please note that I intentionally kept my changes very *separate* from your code, since it will allow me to integrate your future updates easily if you were to not want this feature. The code as you see it can clearly be refactored and adapted if you'd prefer so :)

I'm eager to hear your thoughts on this!

### CODE REVIEW

**Comment by meld-cp** [comment]
Thanks for your hard work @lucabello...  I need some time to digest it

**Comment by Dex321x** [comment]
This would be a really great feature. Hope it can be implemented. Looking forward to use it!

**Comment by Knaledge** [comment]
Any update here? This is essentially a must-have for my use case.

**Comment by motionmitchell** [comment]
Would love to have this too!

**Comment by latif-k** [comment]
Any updates on this? This is a really useful feature.

**Comment by hyliang96** [comment]
Any update now? This feature is necessary for the security of attachments in md notes. It will make a great difference. I would appreciate it if you could add this feature.

**Pull request closed without merging**
